apiVersion: v2
name: calendar-chart
description: A Helm chart for the Calendar application (API, scheduler, sender)
type: application
version: 0.1.0
appVersion: "develop"
keywords:
  - calendar
  - otus
  - golang
